"""add_audit_chain_and_trust_score

Revision ID: 795e4adf7f8b
Revises: 870000000000
Create Date: 2026-08-15 18:38:30.941930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '795e4adf7f8b'
down_revision: Union[str, Sequence[str], None] = '870000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE audit_logs CASCADE")
    
    op.create_table('model_trust_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_trust_scores_timestamp'), 'model_trust_scores', ['timestamp'], unique=False)
    # Preserved checkpoint tables
    op.add_column('audit_logs', sa.Column('seq_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('audit_logs', sa.Column('latency_ms', sa.Float(), nullable=True))
    op.add_column('audit_logs', sa.Column('cost', sa.Numeric(), nullable=True))
    op.add_column('audit_logs', sa.Column('prompt', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('response', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('prev_row_hash', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('current_hash', sa.String(), nullable=True))
    op.execute("ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_pkey CASCADE")
    op.alter_column('audit_logs', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("ALTER TABLE audit_logs ADD PRIMARY KEY (seq_id)")
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audit_logs', 'current_hash')
    op.drop_column('audit_logs', 'prev_row_hash')
    op.drop_column('audit_logs', 'response')
    op.drop_column('audit_logs', 'prompt')
    op.drop_column('audit_logs', 'cost')
    op.drop_column('audit_logs', 'latency_ms')
    op.drop_column('audit_logs', 'seq_id')
    # Checkpoint tables omitted
    op.drop_index(op.f('ix_model_trust_scores_timestamp'), table_name='model_trust_scores')
    op.drop_table('model_trust_scores')
    # ### end Alembic commands ###
