"""add_audit_log_variance_fields

Revision ID: b133f575ef03
Revises: fae04f5ae78f
Create Date: 2026-08-15 20:08:18.157437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b133f575ef03'
down_revision: Union[str, Sequence[str], None] = 'fae04f5ae78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('record_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_record_type'), 'audit_logs', ['record_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_seq_id'), 'audit_logs', ['seq_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_seq_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_type'), table_name='audit_logs')
    op.drop_column('audit_logs', 'record_type')
    op.drop_column('audit_logs', 'session_id')
    # ### end Alembic commands ###
