"""add_expenses_and_budgets

Revision ID: fae04f5ae78f
Revises: 795e4adf7f8b
Create Date: 2026-08-15 19:21:55.746227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fae04f5ae78f'
down_revision: Union[str, Sequence[str], None] = '795e4adf7f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_category'), 'budgets', ['category'], unique=False)
    op.create_index(op.f('ix_budgets_department'), 'budgets', ['department'], unique=False)
    op.create_table('operating_expenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_expenses_category'), 'operating_expenses', ['category'], unique=False)
    op.create_index(op.f('ix_operating_expenses_date'), 'operating_expenses', ['date'], unique=False)
    op.create_index(op.f('ix_operating_expenses_department'), 'operating_expenses', ['department'], unique=False)
    pass # Preserved checkpointer tables
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass # Preserved checkpointer tables
    op.drop_index(op.f('ix_operating_expenses_department'), table_name='operating_expenses')
    op.drop_index(op.f('ix_operating_expenses_date'), table_name='operating_expenses')
    op.drop_index(op.f('ix_operating_expenses_category'), table_name='operating_expenses')
    op.drop_table('operating_expenses')
    op.drop_index(op.f('ix_budgets_department'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
